### PR TITLE
Upgrade to Jekyll 4.3.3

### PR DESCRIPTION
**Pull request by muzimuzhi**
I got an error when running `bundle exec jekyll build`:
```
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:27:in `process'
	from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        ......
```

According to [this discussion](https://talk.jekyllrb.com/t/error-when-executing-bundle-install/8822), upgrading to [Jekyll v4.3.3](https://github.com/jekyll/jekyll/releases/tag/v4.3.3) resolves the backward compatibility issues in the Logger.

This PR is the result of running `bundle update` followed by `bundle exec jekyll build`.

### CODE REVIEW

**Comment by FrankMittelbach** [comment]
given that my setup doesn't have this error, I'm not really keen changing it at the moment as I remember altering the jekyll version can result in a lot of headache for which I right not don't have the time.

**Comment by muzimuzhi** [comment]
Which version of Ruby are you using?

**Comment by FrankMittelbach** [comment]
ruby 3.0.3p157 . As I said I don't really like to touch this any time soon unless I must, because I don't have the time to chaise all the dependencies and I know from past experiences it is like that. Right now it is more important for me to be able to regen the site with ease.

**Comment by josephwright** [comment]
Is this still needed?

**Pull request closed without merging**
